"""create patients table

Revision ID: 81eee582cb57
Revises: 4c3f0075c898
Create Date: 2025-05-17 18:14:29.631487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81eee582cb57'
down_revision: Union[str, None] = '4c3f0075c898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('data_nascimento', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'data_nascimento')
    # ### end Alembic commands ###
